### ISSUE TITLE
Info on workshop topic + CoC + link to event page

### ISSUE THREAD

**Issue by keikoro** [Eleonore9/diverse-coaches#1]
As said else where (: two more suggestions for what could go into the workshop description:
- **workshop topic**, e.g. programming language/technology (as the workshop title/name/"brand" alone might not give enough info or be known by everyone)
- info on if it has a **Code of Conduct**, and ideally a link to it

**Comment by keikoro** [comment]
Ohh, also: along with the workshop name, a _link_ to an online presence of the workshop might make _a lot of sense_ too.

Most workshops probably have an event page somewhere with more info (esp. for participants) and linking potential coaches directly will help them get a better feeling for what the event might be like.

**Comment by Eleonore9** [comment]
Thanks Kay =) I tried to incorporate your suggestions into the Readme.
